# Generated by Django 4.1 on 2023-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_choice_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="voter",
            field=models.IntegerField(default=0),
        ),
    ]
