# Generated by Django 4.1 on 2023-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_choice_voter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="voter",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
