# Generated by Django 4.1 on 2023-02-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_choice_voter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="voter",
            field=models.CharField(max_length=50),
        ),
    ]
